In [ ]:
# Task – 10

In [1]:
import numpy as np
print (np.__version__)

1.26.4


In [2]:
# Exercise Set for Creating Arrays

import numpy as np

array_zeros = np.zeros(8)
print(array_zeros)


[0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
import numpy as np

array_numbers = np.arange(10, 51)
print(array_numbers)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [11]:
import numpy as np

array_matrix = np.arange(9).reshape(3, 3)
print(array_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
import numpy as np
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])
print (a)
print (b)
print (c)

[0 1 2]
[3 4 5]
[6 7 8]


In [12]:
# Exercise Set for Array Indexing and Slicing

a = np.array([0,1,2])
print (a[2])

2


In [13]:
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])
print (b)

[3 4 5]


In [14]:
import numpy as np

array_matrix = np.arange(9).reshape(3, 3)
second_row = array_matrix[1] 
print(second_row)

[3 4 5]


In [15]:
import numpy as np

matrix = np.arange(16).reshape(4, 4)
print("Original Matrix:")
print(matrix)

result = matrix[:2, 2:]
print("\nResult after slicing:")
print(result)


Original Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Result after slicing:
[[2 3]
 [6 7]]


In [16]:
# Exercise Set for Data Types

array = [1.1, 2.2, 3.3]
int_array = [int(element) for element in array]

print(int_array)


[1, 2, 3]


In [21]:
array = [1, 2, 3]
float_array = [float(element) for element in array]
print (float_array)


[1.0, 2.0, 3.0]


In [22]:
# Exercise Set for Copy vs View

a = np.array([5,15,25,35,45])
b = a.copy()
b[0] = 10
b[1] = 20
print (a)
print (b)

[ 5 15 25 35 45]
[10 20 25 35 45]


In [25]:
a = np.array([5,15,25,35,45])
c = a.view()
c[0] = 11
c[1] = 21
print (a)
print (c)


[ 5 15 25 35 45]
[ 5 15 25 35 45]


In [48]:
# Exercise Set for Array Shape and Reshape

import numpy as np

matrix = np.arange(12).reshape(2, 6)

reshaped_matrix = matrix.reshape(3, 4)

print("Original 2x6 matrix:")
print(matrix)
print("\nReshaped 3x4 matrix:")
print(reshaped_matrix)


Original 2x6 matrix:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped 3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
import numpy as np

a = np.array([5,15,25,35,45,55, 65, 75, 85, 95, 105, 115])
reshaped_array = a.reshape(2, 2, 3)
print("Original array of 12 random numbers:")
print(a)
print("\nReshaped 3D array of dimensions 2x2x3:")
print(reshaped_array)


Original array of 12 random numbers:
[  5  15  25  35  45  55  65  75  85  95 105 115]

Reshaped 3D array of dimensions 2x2x3:
[[[  5  15  25]
  [ 35  45  55]]

 [[ 65  75  85]
  [ 95 105 115]]]


In [56]:
# Exercise Set for Array Iterating

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
for row in a : 
    for item in row:
        print (item)

1
2
3
4
5
6
7
8
9


In [64]:
import numpy as np

a = np.array([5,15,25,35,45,55, 65, 75, 85, 95, 105, 115])
for x in np.nditer(a):
    print (x)


5
15
25
35
45
55
65
75
85
95
105
115


In [65]:
# Exercise Set for Array Join

import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6, 7])

z = np.concatenate((x, y))

print (z)


[1 2 3 4 5 6 7]


In [71]:
import numpy as np

x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[7, 8, 9],[10, 11, 12]])
stacked_array = np.vstack((x, y))

print("Array 1:")
print(x)
print("\nArray 2:")
print(y)
print("\nVertically Stacked Array:")
print(stacked_array)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Vertically Stacked Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [72]:
# Exercise Set for Array Split

a = np.array ([5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
new_arrays = np.array_split(a, 3)
print (new_arrays)

[array([5, 6, 7, 8]), array([ 9, 10, 11, 12]), array([13, 14, 15])]


In [82]:
import numpy as np

# Create a 4x4 matrix
matrix = np.array([[0, 1, 2, 3], 
                   [4, 5, 6, 7], 
                   [8, 9, 10, 11], 
                   [12, 13, 14, 15]])

# Horizontally split the matrix into 2 equal parts
hsplit_result = np.hsplit(matrix, 2)

print(hsplit_result)


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [3]:
# Exercise Set for Array Search

import numpy as np
a = np.array([2, 7, 3, 8, 6, 1, 9, 4, 5, 10])
result = np.where(arr > 5)
print("Elements greater than 5:", result)


Elements greater than 5: (array([1, 3, 4, 6, 9], dtype=int64),)


In [4]:
import numpy as np
a = np.array([0, 3, 0, 7, 0, 9, 0])

# Use np.nonzero to find indices of all non-zero elements
nonzero_result = np.nonzero(a)

print("Indices of non-zero elements:", nonzero_result)


Indices of non-zero elements: (array([1, 3, 5], dtype=int64),)


In [7]:
# Exercise Set for Array Sort

import numpy as np

a = np.array ([10, 6, 4, 8, 2, 7, 1, 9, 3, 5])

arr_sorted = np.sort(a)

print("Original array:", a)
print("Sorted array:", arr_sorted)


Original array: [10  6  4  8  2  7  1  9  3  5]
Sorted array: [ 1  2  3  4  5  6  7  8  9 10]


In [11]:
import numpy as np

matrix = np.array([[3, 1, 5],
                   [9, 2, 4],
                   [7, 6, 8]])

sorted_matrix = np.sort(matrix, axis=1)[:, ::-1]

print("Original Matrix:")
print(matrix)

print("\nSorted Matrix (each row in descending order):")
print(sorted_matrix)


Original Matrix:
[[3 1 5]
 [9 2 4]
 [7 6 8]]

Sorted Matrix (each row in descending order):
[[5 3 1]
 [9 4 2]
 [8 7 6]]


In [12]:
# Exercise Set for Array Filter

import numpy as np

a = np.array([16, 25, 27, 10, 8, 4, 90, 93, 23, 87, 99, 32, 67, 43, 21])

# Use boolean indexing to filter out all odd numbers
even_numbers = a[a % 2 == 0]

print("Original array:")
print(a)

print("\nFiltered array (even numbers only):")
print(even_numbers)


Original array:
[16 25 27 10  8  4 90 93 23 87 99 32 67 43 21]

Filtered array (even numbers only):
[16 10  8  4 90 32]


In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
filter = a > 3
result  = a[filter]
print(result)

Original array:
[4 5 6]


In [18]:
# Exercise Set for Random

a = np.random.randint(100, size=(1, 15))
print (a)

[[87 43 85 14 82 70 14 24 45 35 56  5  0 86 92]]


In [19]:
import numpy as np

random_matrix = np.random.rand(3, 3)

print("3x3 Matrix with random floats between 0 and 1:")
print(random_matrix)


3x3 Matrix with random floats between 0 and 1:
[[0.26910885 0.59835596 0.84714694]
 [0.91457232 0.77080962 0.8754916 ]
 [0.33919779 0.70460168 0.00465513]]


In [22]:
# Exercise Set for Operations and Broadcasting

import numpy as np

a = np.array([[1, 2, 3],
             [4, 5, 6]])

b = np.array([[7, 8, 9],
                [10, 11, 12]])
sum = a + b

print("Array 1:")
print(a)

print("\nArray 2:")
print(b)

print("\nResult of element-wise addition:")
print(sum)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Result of element-wise addition:
[[ 8 10 12]
 [14 16 18]]


In [23]:
import numpy as np

# Create an array of shape (4,)
array1 = np.array([1, 2, 3, 4])

# Create an array of shape (4, 1)
array2 = np.array([[10],
                   [20],
                   [30],
                   [40]])

# Use broadcasting to add the arrays
result_array = array1 + array2

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nResult of broadcasting addition:")
print(result_array)


Array 1:
[1 2 3 4]

Array 2:
[[10]
 [20]
 [30]
 [40]]

Result of broadcasting addition:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
